### ISSUE TITLE
Broke with latest obsidian update

### ISSUE THREAD

**Issue by skorphil** [mugiwara85/CodeblockCustomizer#60]
Hi, thanks for great plugin. Unfortunately it prevents the new version 1.14.16 of obsidian to work.
With a plugin enabled obsidian not opening md files - it writes "no file selected".

Console output:
```
plugin:codeblock-customizer:7958 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'common')
    at create (plugin:codeblock-customizer:7958:62)
    at e.create (app.js:1:326883)
    at Object.create (app.js:1:326991)
    at e.computeSlot (app.js:1:340050)
    at tr (app.js:1:330991)
    at new e (app.js:1:336866)
    at e.create (app.js:1:339968)
    at t.clear (app.js:1:1259462)
    at t [as constructor] (app.js:1:1256527)
    at new t (app.js:1:2077556)
```

**Comment by mugiwara85** [comment]
It does work, but apparently you have a very old version installed. Can you send the installed plugin version?
Uninstall the plugin and reinstall it. Make sure that after uninstalling the plugin, the data.json file is removed.

**Comment by mugiwara85** [comment]
Or the plugin is updated, but you forgot to remove the data.json file. There was a bigger change a few versions ago, which required removing the data.json file.

**Comment by mugiwara85** [comment]
In your PluginFolder\.obsidian\plugins\codeblock-customizer\
